# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_which_in <- function(x, tbl) {
    .Call(`_hutilscpp_do_which_in`, x, tbl)
}

test_intersect3_stdint <- function(M = 0L) {
    .Call(`_hutilscpp_test_intersect3_stdint`, M)
}

do_par_in <- function(x, table, nThread = 1L) {
    .Call(`_hutilscpp_do_par_in`, x, table, nThread)
}

do_par_in_hash_int <- function(x, table, nThread = 1L) {
    .Call(`_hutilscpp_do_par_in_hash_int`, x, table, nThread)
}

do_par_in_hash_dbl <- function(x, table, nThread = 1L) {
    .Call(`_hutilscpp_do_par_in_hash_dbl`, x, table, nThread)
}

do_which_first_xi_ini <- function(x, y) {
    .Call(`_hutilscpp_do_which_first_xi_ini`, x, y)
}

dblTable2int <- function(table) {
    .Call(`_hutilscpp_dblTable2int`, table)
}

do_which_first_xi_ind <- function(x, yd) {
    .Call(`_hutilscpp_do_which_first_xi_ind`, x, yd)
}

do_which_first_xd_ind <- function(x, y, y_has_na) {
    .Call(`_hutilscpp_do_which_first_xd_ind`, x, y, y_has_na)
}

do_which_last_xi_ini <- function(x, y) {
    .Call(`_hutilscpp_do_which_last_xi_ini`, x, y)
}

do_which_last_xi_ind <- function(x, yd) {
    .Call(`_hutilscpp_do_which_last_xi_ind`, x, yd)
}

do_which_last_xd_ind <- function(x, y, y_has_na) {
    .Call(`_hutilscpp_do_which_last_xd_ind`, x, y, y_has_na)
}

showValue <- function(what, x) {
    invisible(.Call(`_hutilscpp_showValue`, what, x))
}

haversine_distance <- function(olat1, olon1, olat2, olon2, unitless = FALSE) {
    .Call(`_hutilscpp_haversine_distance`, olat1, olon1, olat2, olon2, unitless)
}

haversineDistance <- function(lat1, lon1, lat2, lon2, unitless = FALSE) {
    .Call(`_hutilscpp_haversineDistance`, lat1, lon1, lat2, lon2, unitless)
}

theEuclidDistance <- function(x1, x2, y1, y2, unitless = FALSE) {
    .Call(`_hutilscpp_theEuclidDistance`, x1, x2, y1, y2, unitless)
}

hausdorffEuclid <- function(x, y) {
    .Call(`_hutilscpp_hausdorffEuclid`, x, y)
}

EmptiestQuarter <- function(x, y, minx = 1, maxx = -1, miny = 1, maxy = -1) {
    .Call(`_hutilscpp_EmptiestQuarter`, x, y, minx, maxx, miny, maxy)
}

theEmptiestQuarters <- function(x, y, minx = 1, maxx = -1, miny = 1, maxy = -1, depth = 4L) {
    .Call(`_hutilscpp_theEmptiestQuarters`, x, y, minx, maxx, miny, maxy, depth)
}

which_min_HaversineDistance <- function(lat1, lon1, lat2, lon2, upperBound = 10) {
    .Call(`_hutilscpp_which_min_HaversineDistance`, lat1, lon1, lat2, lon2, upperBound)
}

match_min_Haversine <- function(lat1, lon1, lat2, lon2, tabl, cartR = -1, dist0_km = 0.01, verify_cartR = FALSE, do_verify_box = FALSE, excl_self = FALSE, ncores = 1L) {
    .Call(`_hutilscpp_match_min_Haversine`, lat1, lon1, lat2, lon2, tabl, cartR, dist0_km, verify_cartR, do_verify_box, excl_self, ncores)
}

do_or3 <- function(x, y, z) {
    .Call(`_hutilscpp_do_or3`, x, y, z)
}

do_and3 <- function(x, y, z) {
    .Call(`_hutilscpp_do_and3`, x, y, z)
}

na_and <- function(x) {
    .Call(`_hutilscpp_na_and`, x)
}

do_which3 <- function(x, y, z, And = TRUE, anyNAx = TRUE, anyNAy = TRUE, anyNAz = TRUE) {
    .Call(`_hutilscpp_do_which3`, x, y, z, And, anyNAx, anyNAy, anyNAz)
}

do_which3_mem <- function(x, y, z, And = TRUE) {
    .Call(`_hutilscpp_do_which3_mem`, x, y, z, And)
}

has_openmp <- function() {
    .Call(`_hutilscpp_has_openmp`)
}

diagnose_omp <- function(threads_requested, msg_no_openmp, msg_threads_neg, msg_unknown_issues, msg_too_many_threads) {
    .Call(`_hutilscpp_diagnose_omp`, threads_requested, msg_no_openmp, msg_threads_neg, msg_unknown_issues, msg_too_many_threads)
}

