# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AnyCharMatch <- function(x, a, opposite = FALSE) {
    .Call(`_hutilscpp_AnyCharMatch`, x, a, opposite)
}

Implies <- function(x, y, anyNAx = TRUE, anyNAy = TRUE) {
    .Call(`_hutilscpp_Implies`, x, y, anyNAx, anyNAy)
}

is_altrep <- function(x) {
    .Call(`_hutilscpp_is_altrep`, x)
}

allocate0_int <- function(N, nThread = 1L) {
    .Call(`_hutilscpp_allocate0_int`, N, nThread)
}

allocate0_dbl <- function(N, nThread = 1L) {
    .Call(`_hutilscpp_allocate0_dbl`, N, nThread)
}

allocate0_except <- function(N, India, Victor, nThread = 1L) {
    .Call(`_hutilscpp_allocate0_except`, N, India, Victor, nThread)
}

allocate_with_root <- function(N, a, r, left, do_pmin, nThread = 1L) {
    .Call(`_hutilscpp_allocate_with_root`, N, a, r, left, do_pmin, nThread)
}

anyOutside_int <- function(x, a, b, nas_present = FALSE, na_is_outside = TRUE) {
    .Call(`_hutilscpp_anyOutside_int`, x, a, b, nas_present, na_is_outside)
}

anyOutside_dbl <- function(x, a, b, nas_present = FALSE, na_is_outside = TRUE) {
    .Call(`_hutilscpp_anyOutside_dbl`, x, a, b, nas_present, na_is_outside)
}

do_range_dbl <- function(x, halt_if_min = 1, halt_if_max = -1) {
    .Call(`_hutilscpp_do_range_dbl`, x, halt_if_min, halt_if_max)
}

do_range_int <- function(x, halt_if_min = 1L, halt_if_max = -1L) {
    .Call(`_hutilscpp_do_range_int`, x, halt_if_min, halt_if_max)
}

do_and3_par <- function(x, ox, x1, x2, y, oy, y1, y2, z, oz, z1, z2, A, B, C, nom, nThread = 1L) {
    .Call(`_hutilscpp_do_and3_par`, x, ox, x1, x2, y, oy, y1, y2, z, oz, z1, z2, A, B, C, nom, nThread)
}

do_sum3s_par <- function(x, ox, x1, x2, xd, xd1, xd2, y, oy, y1, y2, yd, yd1, yd2, z, oz, z1, z2, zd, zd1, zd2, A, B, C, ampersand = TRUE, nThread = 1L) {
    .Call(`_hutilscpp_do_sum3s_par`, x, ox, x1, x2, xd, xd1, xd2, y, oy, y1, y2, yd, yd1, yd2, z, oz, z1, z2, zd, zd1, zd2, A, B, C, ampersand, nThread)
}

do_cumsum_reset_logical <- function(x) {
    .Call(`_hutilscpp_do_cumsum_reset_logical`, x)
}

do_cumsum_reset_integer <- function(x, y) {
    .Call(`_hutilscpp_do_cumsum_reset_integer`, x, y)
}

do_cumsum_reset_double <- function(x, y) {
    .Call(`_hutilscpp_do_cumsum_reset_double`, x, y)
}

do_duplicated_sorted_int <- function(x) {
    .Call(`_hutilscpp_do_duplicated_sorted_int`, x)
}

do_duplicated_sorted_dbl <- function(x) {
    .Call(`_hutilscpp_do_duplicated_sorted_dbl`, x)
}

do_cumsum_reset_sorted_int <- function(x) {
    .Call(`_hutilscpp_do_cumsum_reset_sorted_int`, x)
}

do_divisible <- function(x, d, nThread = 1L) {
    .Call(`_hutilscpp_do_divisible`, x, d, nThread)
}

do_divisible2 <- function(x, nThread = 1L) {
    .Call(`_hutilscpp_do_divisible2`, x, nThread)
}

do_divisible16 <- function(x, nThread = 1L) {
    .Call(`_hutilscpp_do_divisible16`, x, nThread)
}

do_are_even <- function(x, y, wb = 0L, nThread = 1L) {
    .Call(`_hutilscpp_do_are_even`, x, y, wb, nThread)
}

do_which_even <- function(x, y, wb = 0L) {
    .Call(`_hutilscpp_do_which_even`, x, y, wb)
}

do_and3_na <- function(x, y, z, nThread = 1L, na_value = 0L, maxCall = 3L) {
    .Call(`_hutilscpp_do_and3_na`, x, y, z, nThread, na_value, maxCall)
}

do_which2_yr <- function(Year, yr, consider_yr, x, xa, eqx, gtx, ltx, y, ya, eqy, gty, lty) {
    .Call(`_hutilscpp_do_which2_yr`, Year, yr, consider_yr, x, xa, eqx, gtx, ltx, y, ya, eqy, gty, lty)
}

do_which_in <- function(x, tbl) {
    .Call(`_hutilscpp_do_which_in`, x, tbl)
}

test_intersect3_stdint <- function(M = 0L) {
    .Call(`_hutilscpp_test_intersect3_stdint`, M)
}

do_count_logical <- function(x, nThread = 1L) {
    .Call(`_hutilscpp_do_count_logical`, x, nThread)
}

do_count_logical_long <- function(x, nThread = 1L) {
    .Call(`_hutilscpp_do_count_logical_long`, x, nThread)
}

do_in_int <- function(x, table) {
    .Call(`_hutilscpp_do_in_int`, x, table)
}

do_par_in <- function(x, table, nThread = 1L) {
    .Call(`_hutilscpp_do_par_in`, x, table, nThread)
}

do_par_in_hash_int <- function(x, table, nThread = 1L) {
    .Call(`_hutilscpp_do_par_in_hash_int`, x, table, nThread)
}

do_par_in_hash_dbl <- function(x, table, nThread = 1L) {
    .Call(`_hutilscpp_do_par_in_hash_dbl`, x, table, nThread)
}

do_op2M <- function(x) {
    .Call(`_hutilscpp_do_op2M`, x)
}

do_or3_par <- function(x, ox, x1, x2, y, oy, y1, y2, z, oz, z1, z2, A, B, C, nom, nThread = 1L) {
    .Call(`_hutilscpp_do_or3_par`, x, ox, x1, x2, y, oy, y1, y2, z, oz, z1, z2, A, B, C, nom, nThread)
}

do_range_dbl_simple <- function(x) {
    .Call(`_hutilscpp_do_range_dbl_simple`, x)
}

do_which_first <- function(x) {
    .Call(`_hutilscpp_do_which_first`, x)
}

do_which_last <- function(x) {
    .Call(`_hutilscpp_do_which_last`, x)
}

do_which_first_false <- function(x) {
    .Call(`_hutilscpp_do_which_first_false`, x)
}

do_which_last_false <- function(x) {
    .Call(`_hutilscpp_do_which_last_false`, x)
}

do_which_first_notTRUE <- function(x) {
    .Call(`_hutilscpp_do_which_first_notTRUE`, x)
}

do_which_last_notTRUE <- function(x) {
    .Call(`_hutilscpp_do_which_last_notTRUE`, x)
}

do_which_last_notFALSE <- function(x) {
    .Call(`_hutilscpp_do_which_last_notFALSE`, x)
}

do_which_first_in_lgl <- function(x, anyNA_, any_, nall_) {
    .Call(`_hutilscpp_do_which_first_in_lgl`, x, anyNA_, any_, nall_)
}

do_which_firstNA <- function(x) {
    .Call(`_hutilscpp_do_which_firstNA`, x)
}

do_which_lastNA <- function(x) {
    .Call(`_hutilscpp_do_which_lastNA`, x)
}

do_which_first_lgl_lgl_op <- function(x, y, op, reverse = FALSE) {
    .Call(`_hutilscpp_do_which_first_lgl_lgl_op`, x, y, op, reverse)
}

do_which_first__ <- function(x, op, y, ny, y1i, y2i, y1d, y2d) {
    .Call(`_hutilscpp_do_which_first__`, x, op, y, ny, y1i, y2i, y1d, y2d)
}

do_which_first_xi_ini <- function(x, y) {
    .Call(`_hutilscpp_do_which_first_xi_ini`, x, y)
}

dblTable2int <- function(table) {
    .Call(`_hutilscpp_dblTable2int`, table)
}

do_which_first_xi_ind <- function(x, yd) {
    .Call(`_hutilscpp_do_which_first_xi_ind`, x, yd)
}

do_which_first_xd_ind <- function(x, y, y_has_na) {
    .Call(`_hutilscpp_do_which_first_xd_ind`, x, y, y_has_na)
}

do_which_isnt_integerish <- function(x) {
    .Call(`_hutilscpp_do_which_isnt_integerish`, x)
}

do_which_last_xd_ad <- function(x, op, a) {
    .Call(`_hutilscpp_do_which_last_xd_ad`, x, op, a)
}

do_which_last_xi_ai <- function(x, op, a) {
    .Call(`_hutilscpp_do_which_last_xi_ai`, x, op, a)
}

do_which_last_xi_ad <- function(x, op, ad) {
    .Call(`_hutilscpp_do_which_last_xi_ad`, x, op, ad)
}

do_which_last_xd_yd <- function(x, op, y) {
    .Call(`_hutilscpp_do_which_last_xd_yd`, x, op, y)
}

do_which_last_xi_yi <- function(x, op, y) {
    .Call(`_hutilscpp_do_which_last_xi_yi`, x, op, y)
}

do_which_last_xi_yd <- function(x, op, y) {
    .Call(`_hutilscpp_do_which_last_xi_yd`, x, op, y)
}

do_which_last_xd_yi <- function(x, op, y) {
    .Call(`_hutilscpp_do_which_last_xd_yi`, x, op, y)
}

do_which_last_xd_add <- function(x, op, a1, a2) {
    .Call(`_hutilscpp_do_which_last_xd_add`, x, op, a1, a2)
}

do_which_last__ <- function(x, op, y, ny, y1i, y2i, y1d, y2d) {
    .Call(`_hutilscpp_do_which_last__`, x, op, y, ny, y1i, y2i, y1d, y2d)
}

do_which_last_in_lgl <- function(x, anyNA_, any_, nall_) {
    .Call(`_hutilscpp_do_which_last_in_lgl`, x, anyNA_, any_, nall_)
}

do_which_last_xi_ini <- function(x, y) {
    .Call(`_hutilscpp_do_which_last_xi_ini`, x, y)
}

do_which_last_xi_ind <- function(x, yd) {
    .Call(`_hutilscpp_do_which_last_xi_ind`, x, yd)
}

do_which_last_xd_ind <- function(x, y, y_has_na) {
    .Call(`_hutilscpp_do_which_last_xd_ind`, x, y, y_has_na)
}

do_whichs_16 <- function(op, x, y, nThread = 1L) {
    .Call(`_hutilscpp_do_whichs_16`, op, x, y, nThread)
}

do_xor2 <- function(x, y, anyNAx = TRUE, anyNAy = TRUE) {
    .Call(`_hutilscpp_do_xor2`, x, y, anyNAx, anyNAy)
}

showValue <- function(what, x) {
    invisible(.Call(`_hutilscpp_showValue`, what, x))
}

haversine_distance <- function(olat1, olon1, olat2, olon2, unitless = FALSE) {
    .Call(`_hutilscpp_haversine_distance`, olat1, olon1, olat2, olon2, unitless)
}

haversineDistance <- function(lat1, lon1, lat2, lon2, unitless = FALSE) {
    .Call(`_hutilscpp_haversineDistance`, lat1, lon1, lat2, lon2, unitless)
}

theEuclidDistance <- function(x1, x2, y1, y2, unitless = FALSE) {
    .Call(`_hutilscpp_theEuclidDistance`, x1, x2, y1, y2, unitless)
}

hausdorffEuclid <- function(x, y) {
    .Call(`_hutilscpp_hausdorffEuclid`, x, y)
}

EmptiestQuarter <- function(x, y, minx = 1, maxx = -1, miny = 1, maxy = -1) {
    .Call(`_hutilscpp_EmptiestQuarter`, x, y, minx, maxx, miny, maxy)
}

theEmptiestQuarters <- function(x, y, minx = 1, maxx = -1, miny = 1, maxy = -1, depth = 4L) {
    .Call(`_hutilscpp_theEmptiestQuarters`, x, y, minx, maxx, miny, maxy, depth)
}

which_min_HaversineDistance <- function(lat1, lon1, lat2, lon2, upperBound = 10) {
    .Call(`_hutilscpp_which_min_HaversineDistance`, lat1, lon1, lat2, lon2, upperBound)
}

match_min_Haversine <- function(lat1, lon1, lat2, lon2, tabl, cartR = -1, dist0_km = 0.01, verify_cartR = FALSE, do_verify_box = FALSE, excl_self = FALSE, ncores = 1L) {
    .Call(`_hutilscpp_match_min_Haversine`, lat1, lon1, lat2, lon2, tabl, cartR, dist0_km, verify_cartR, do_verify_box, excl_self, ncores)
}

all_na_real <- function(x, nThread = 1L) {
    .Call(`_hutilscpp_all_na_real`, x, nThread)
}

do_isntConstant_dbl <- function(x) {
    .Call(`_hutilscpp_do_isntConstant_dbl`, x)
}

do_is_constant <- function(x, nThread = 1L) {
    .Call(`_hutilscpp_do_is_constant`, x, nThread)
}

do_isntConstant <- function(x) {
    .Call(`_hutilscpp_do_isntConstant`, x)
}

#' @noRd
#' @param x Candidate vector.
#' @return
#'   0 if unsafe to coerce to integer
#'   1 if   safe to coerce to integer and _zero_ NAs in output
#'   2 if   safe to coerce to integer but _some_ NAs in output
is_safe2int <- function(x) {
    .Call(`_hutilscpp_is_safe2int`, x)
}

force_as_integer <- function(x, na_code) {
    .Call(`_hutilscpp_force_as_integer`, x, na_code)
}

is_sorted_ascending_dbl <- function(x) {
    .Call(`_hutilscpp_is_sorted_ascending_dbl`, x)
}

is_sorted_descending_dbl <- function(x) {
    .Call(`_hutilscpp_is_sorted_descending_dbl`, x)
}

is_sorted_ascending_int <- function(x) {
    .Call(`_hutilscpp_is_sorted_ascending_int`, x)
}

is_sorted_descending_int <- function(x) {
    .Call(`_hutilscpp_is_sorted_descending_int`, x)
}

is_sorted_int <- function(x) {
    .Call(`_hutilscpp_is_sorted_int`, x)
}

do_isntSorted_int <- function(x) {
    .Call(`_hutilscpp_do_isntSorted_int`, x)
}

is_sorted_dbl <- function(x) {
    .Call(`_hutilscpp_is_sorted_dbl`, x)
}

do_isntSorted_dbl <- function(x) {
    .Call(`_hutilscpp_do_isntSorted_dbl`, x)
}

do_or3 <- function(x, y, z) {
    .Call(`_hutilscpp_do_or3`, x, y, z)
}

do_and3 <- function(x, y, z) {
    .Call(`_hutilscpp_do_and3`, x, y, z)
}

na_and <- function(x) {
    .Call(`_hutilscpp_na_and`, x)
}

do_which3 <- function(x, y, z, And = TRUE, anyNAx = TRUE, anyNAy = TRUE, anyNAz = TRUE) {
    .Call(`_hutilscpp_do_which3`, x, y, z, And, anyNAx, anyNAy, anyNAz)
}

do_which3_mem <- function(x, y, z, And = TRUE) {
    .Call(`_hutilscpp_do_which3_mem`, x, y, z, And)
}

has_openmp <- function() {
    .Call(`_hutilscpp_has_openmp`)
}

diagnose_omp <- function(threads_requested, msg_no_openmp, msg_threads_neg, msg_unknown_issues, msg_too_many_threads) {
    .Call(`_hutilscpp_diagnose_omp`, threads_requested, msg_no_openmp, msg_threads_neg, msg_unknown_issues, msg_too_many_threads)
}

do_firstNonNegativeRadix_int <- function(x, mini = 0L, maxi = -1L, desc = FALSE, depth = 0L) {
    .Call(`_hutilscpp_do_firstNonNegativeRadix_int`, x, mini, maxi, desc, depth)
}

do_firstNonNegativeRadix_dbl <- function(x, mini = 0L, maxi = -1L, desc = FALSE, depth = 0L) {
    .Call(`_hutilscpp_do_firstNonNegativeRadix_dbl`, x, mini, maxi, desc, depth)
}

do_pmax0_radix_sorted_dbl <- function(x, in_place = FALSE, nThread = 1L) {
    .Call(`_hutilscpp_do_pmax0_radix_sorted_dbl`, x, in_place, nThread)
}

do_pmin0_radix_sorted_dbl <- function(x, in_place = FALSE, nThread = 1L) {
    .Call(`_hutilscpp_do_pmin0_radix_sorted_dbl`, x, in_place, nThread)
}

do_pmax0_radix_sorted_int <- function(x, in_place = FALSE, nThread = 1L) {
    .Call(`_hutilscpp_do_pmax0_radix_sorted_int`, x, in_place, nThread)
}

do_pmin0_radix_sorted_int <- function(x, in_place = FALSE, nThread = 1L) {
    .Call(`_hutilscpp_do_pmin0_radix_sorted_int`, x, in_place, nThread)
}

do_pmax0_bitwise <- function(x, nThread = 1L) {
    .Call(`_hutilscpp_do_pmax0_bitwise`, x, nThread)
}

do_pmin0_bitwise <- function(x, nThread = 1L) {
    .Call(`_hutilscpp_do_pmin0_bitwise`, x, nThread)
}

do_pminpmax <- function(X, Y, do_min = FALSE, in_place = FALSE, keep_nas = FALSE, dbl_ok = FALSE, swap_xy = FALSE, nThread = 1L) {
    .Call(`_hutilscpp_do_pminpmax`, X, Y, do_min, in_place, keep_nas, dbl_ok, swap_xy, nThread)
}

squishn <- function(x, a, b, in_place = FALSE) {
    .Call(`_hutilscpp_squishn`, x, a, b, in_place)
}

squishi <- function(x, a, b, in_place = FALSE) {
    .Call(`_hutilscpp_squishi`, x, a, b, in_place)
}

sum_isna_int <- function(x, nThread = 1L) {
    .Call(`_hutilscpp_sum_isna_int`, x, nThread)
}

sum_isna_dbl <- function(x, nThread = 1L) {
    .Call(`_hutilscpp_sum_isna_dbl`, x, nThread)
}

sum_isna_complx <- function(x, nThread = 1L) {
    .Call(`_hutilscpp_sum_isna_complx`, x, nThread)
}

sum_isna_char <- function(x, nThread = 1L) {
    .Call(`_hutilscpp_sum_isna_char`, x, nThread)
}

sum_isfalse <- function(x, nThread = 1L) {
    .Call(`_hutilscpp_sum_isfalse`, x, nThread)
}

sum_isna_logi <- function(x, nThread = 1L) {
    .Call(`_hutilscpp_sum_isna_logi`, x, nThread)
}

do_summary3_dbl <- function(x, y, z, in_place = FALSE, do_max = TRUE) {
    .Call(`_hutilscpp_do_summary3_dbl`, x, y, z, in_place, do_max)
}

do_summary3_int <- function(x, y, z, in_place = FALSE, do_max = TRUE) {
    .Call(`_hutilscpp_do_summary3_int`, x, y, z, in_place, do_max)
}

test_single_ox_x1_x2 <- function(x, op, x1, x2) {
    .Call(`_hutilscpp_test_single_ox_x1_x2`, x, op, x1, x2)
}

#' @name where_square_bracket_opens
#' @param x Character vector of characters.
#' @param i position of closing bracket.
#'
#' @return
#' -1 if x[i] does not closing bracket
#'  0 if bracket never closes
#'  j the location of the closing brace
#'
#' @noRd
NULL

validate_nchar1 <- function(x, return_size = FALSE) {
    .Call(`_hutilscpp_validate_nchar1`, x, return_size)
}

max_charsize <- function(x) {
    .Call(`_hutilscpp_max_charsize`, x)
}

is_space <- function(x) {
    .Call(`_hutilscpp_is_space`, x)
}

where_square_bracket_opens <- function(x, i = 0L) {
    .Call(`_hutilscpp_where_square_bracket_opens`, x, i)
}

extractMandatory <- function(x, command, nCommands) {
    .Call(`_hutilscpp_extractMandatory`, x, command, nCommands)
}

do_which_true_onwards <- function(x) {
    .Call(`_hutilscpp_do_which_true_onwards`, x)
}

