# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Quickly verify (and locate) the existence of a breach.
#' @name AnyWhich
#' @description Used when a single instance is likely to occur and be important to detect quickly
#' (in a sufficiently large integer vector).
#' @param x An integer vector.
#' @param a A (single) integer. That which is to be compared.
#' @param gt,lt,eq Booleans, whether or not the comparison is greater than, less than, or equal to.
#' Only \code{gt} and \code{lt} are mutually exclusive. If all \code{FALSE}, find the first instance
#' where none are equal (i.e. does \code{x} have more than one distinct value).
#'
NULL

AnyWhich <- function(x, a, gt, lt, eq) {
    .Call(`_hutilscpp_AnyWhich`, x, a, gt, lt, eq)
}

ModeInt <- function(x) {
    .Call(`_hutilscpp_ModeInt`, x)
}

#' @title Mode II
#' @param x Integer vector
#' @export ModeInt2
#' @name ModeInt2
NULL

ModeInt2 <- function(x, xmax = -1L, xmin = 1L) {
    .Call(`_hutilscpp_ModeInt2`, x, xmax, xmin)
}

anyOutside <- function(x, a, b) {
    .Call(`_hutilscpp_anyOutside`, x, a, b)
}

do_cumsum_reset_logical <- function(x) {
    .Call(`_hutilscpp_do_cumsum_reset_logical`, x)
}

do_cumsum_reset_integer <- function(x, y) {
    .Call(`_hutilscpp_do_cumsum_reset_integer`, x, y)
}

do_cumsum_reset_double <- function(x, y) {
    .Call(`_hutilscpp_do_cumsum_reset_double`, x, y)
}

do_which_first <- function(x) {
    .Call(`_hutilscpp_do_which_first`, x)
}

do_which_last <- function(x) {
    .Call(`_hutilscpp_do_which_last`, x)
}

do_which_first_false <- function(x) {
    .Call(`_hutilscpp_do_which_first_false`, x)
}

#' @title Threeway parallel maximum
#' @description Returns the parallel maximum of three 
#' 
#' @name pmax3
#' @param x,y,z Numeric vectors of identical lengths.
#' @return The parallel maximum of the vectors.
#' @export pmax3
NULL

pmax3 <- function(x, y, z) {
    .Call(`_hutilscpp_pmax3`, x, y, z)
}

#' @name do_pmaxC
#' @title Internal pmaxC helpers
#' @description Internal functions used when the overheads of assertions
#' would be too expensive.
#' @param x A numeric/integer vector.
#' @param a A single numeric/integer.
#' @export do_pmaxC_dbl do_pmaxC_int do_pmax0 do_pmaxIPint0 do_pmaxIPnum0
NULL

#' @rdname do_pmaxC
do_pmaxC_dbl <- function(x, a) {
    .Call(`_hutilscpp_do_pmaxC_dbl`, x, a)
}

#' @rdname do_pmaxC
do_pmaxC_int <- function(x, a) {
    .Call(`_hutilscpp_do_pmaxC_int`, x, a)
}

#' @rdname do_pmaxC
do_pmax0 <- function(x) {
    .Call(`_hutilscpp_do_pmax0`, x)
}

#' @rdname do_pmaxC
do_pmaxIPnum0 <- function(x) {
    .Call(`_hutilscpp_do_pmaxIPnum0`, x)
}

#' @rdname do_pmaxC
do_pmaxIPint0 <- function(x) {
    .Call(`_hutilscpp_do_pmaxIPint0`, x)
}

#' @title Parallel maximum in C++
#' @description A faster \code{pmax()}.
#'
#' @name do_pmaxV
#' @param x A numeric vector.
#' @param y A numeric vector, the same length as x.
#' @return The parallel maximum of the input values.
#' @export do_pmaxNumNum do_pmaxIntInt
NULL

#' @rdname do_pmaxV
do_pmaxNumNum <- function(x, y) {
    .Call(`_hutilscpp_do_pmaxNumNum`, x, y)
}

#' @rdname do_pmaxV
do_pmaxIntInt <- function(x, y) {
    .Call(`_hutilscpp_do_pmaxIntInt`, x, y)
}

#' @title Parallel maximum
#' @description A faster \code{pmin()}.
#'
#' @name do_pminC
#' @param x A numeric vector.
#' @param a A single numeric value.
#' @return The parallel minimum of the input values. The \code{0} versions are shortcuts for \code{a = 0}.
#' @note This function will always be faster than \code{pmin(x, a)} when \code{a} is a single value, but can be slower than \code{pmin.int(x, a)} when \code{x} is short. Use this function when comparing a numeric vector with a single value.
#' @export do_pminC
NULL

do_pminC <- function(x, a) {
    .Call(`_hutilscpp_do_pminC`, x, a)
}

do_pmin0 <- function(x) {
    .Call(`_hutilscpp_do_pmin0`, x)
}

#' @title Parallel maximum
#' @description A faster \code{pmin()}.
#'
#' @name do_pminV
#' @param x A numeric vector.
#' @param y A numeric vector, the same length as x.
#' @return The parallel maximum of the input values.
#' @export do_pminV
NULL

do_pminV <- function(x, y) {
    .Call(`_hutilscpp_do_pminV`, x, y)
}

squishn <- function(x, a, b) {
    .Call(`_hutilscpp_squishn`, x, a, b)
}

squishi <- function(x, a, b) {
    .Call(`_hutilscpp_squishi`, x, a, b)
}

texParse <- function(open, close, maxTeXGroup = 20L) {
    .Call(`_hutilscpp_texParse`, open, close, maxTeXGroup)
}

do_which_true_onwards <- function(x) {
    .Call(`_hutilscpp_do_which_true_onwards`, x)
}

