name: Check
'on': push
jobs:
  build:
    name: covr
    runs-on: ubuntu-latest
    env:
      TT_AT_HOME: "TRUE"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages(c('rcmdcheck', 'remotes', 'covr'), repos = 'https://cran.rstudio.com')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = https://cran.rstudio.com')"
      - name: codecov
        run: Rscript -e "covr::codecov(quiet = FALSE)"
    container: rocker/verse:latest
  rcmdchecker:
    name: Rcmdcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck
        needs: check
    - uses: r-lib/actions/check-r-package@v2
    container: rocker/verse:latest
  test-r-sanitizers:
    name: ASAN-UBSAN
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: rhub/rocker-gcc-san
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 5
          submodules: true
      - name: Install packages
        shell: bash
        run: |
          Rdevel -q -e "ip <- function(x) install.packages(x[!sapply(x, requireNamespace, quietly = TRUE)], quiet = TRUE, repos = 'https://cran.r-project.org'); ip(c('tinytest', 'data.table', 'glue', 'hutils', 'magrittr'))"
          Rdevel CMD build .
          Rdevel CMD INSTALL --install-tests hutilscpp*.tar.gz
          Rdevel -q -e "hutilscpp:::unsafe_int(2147483648)"
          Rdevel -q -e "tinytest::run_test_file(file = 'inst/tinytest/test-valgrind.R')"
