name: Check
'on': push
jobs:
  build:
    name: covr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages(c('rcmdcheck', 'remotes', 'covr'), repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - name: codecov
        run: Rscript -e "covr::codecov(quiet = FALSE)"
    container: rocker/verse:latest
  rcmdchecker:
    name: Rcmdcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Package Dependencies
        run: |-
            Rscript -e "install.packages(c('rcmdcheck', 'remotes'), repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
            Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - name: Run Check
        run: Rscript -e "rcmdcheck::rcmdcheck(build_args = '--no-manual')"
    container: rocker/verse:latest
  rchk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: r-lib/actions/run-rchk@master
  test-r-sanitizers:
    name: ASAN-UBSAN
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: rhub/rocker-gcc-san
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 5
          submodules: true
      - name: Install packages
        shell: bash
        run: |
          Rdevel -q -e "ip <- function(x) install.packages(x[!sapply(x, requireNamespace, quietly = TRUE)], quiet = TRUE, repos = 'https://cran.r-project.org'); ip(c('testthat', 'data.table', 'glue', 'hutils', 'magrittr'))"
          Rdevel CMD build .
          Rdevel CMD INSTALL --install-tests hutilscpp*.tar.gz
          Rdevel -q -e "max(sapply(dir(path = find.package('hutilscpp'), recursive = TRUE, full.names = TRUE), function(x) file.size(x) / 1024))"
          Rdevel -q -e "library(hutilscpp); expr <- c(0L, 5L, 3L, 2L); o <- 0; for (i in 1:1000) o <- o + which_first(expr %in% c(8L, 9L))"
          Rdevel -q -e "z3 <- integer(3); hutilscpp::which_first(z3 == NaN)"
          Rdevel -q -e "z3 <- integer(3); hutilscpp::which_first(z3 != NaN)"
          Rdevel -q -e "z3 <- integer(3); hutilscpp::which_first(z3 >= 2147483647.1)"
          Rdevel -q -e "z3 <- integer(3); hutilscpp:::first_which(z3 >= 2147483647.1)"
          Rdevel -q -e "z3 <- integer(3); hutilscpp::which_last(z3 >= -2147483647.1)"
          Rdevel -q -e "z3 <- c(0L, 1:9); hutilscpp::which_last(z3 >= -2147483647.1)"
          Rdevel -q -e "z3 <- integer(3); hutilscpp::which_last(z3 >= -2147483647.1)"
          Rdevel -q -e "testthat::test_package('hutilscpp', reporter = testthat::LocationReporter, filter = 'fmatch|which')"
          Rdevel -q -e "z3 <- c(0L, 1:9, -2147483647L); hutilscpp::which_last(z3 >= -2147483647)"
          Rdevel -q -e "z3 <- c(0L, 1:9, -2147483647L); hutilscpp::which_last(z3 < -2147483647)"
