name: Render and Deploy RMarkdown Website
'on': push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages(c('rcmdcheck', 'remotes', 'covr'), repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - name: codecov
        run: Rscript -e "covr::codecov()"
    container: rocker/verse:latest
  test-r-sanitizers:
    name: r-package (ubuntu-latest, R-devel, GCC ASAN/UBSAN)
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: rhub/rocker-gcc-san
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 5
          submodules: true
      - name: Install packages
        shell: bash
        run: |
          Rdevel -q -e "ip <- function(x) install.packages(x, quiet = TRUE, repos = 'https://cran.r-project.org'); ip(c('Rcpp', 'data.table', 'glue', 'hutils', 'magrittr'))"
          Rdevel CMD build .
          Rdevel CMD INSTALL hutilscpp*.tar.gz
          Rdevel -q -e "file.size(system.file("src", "hutilscpp.dll", package = "hutilscpp")) / 1024"
          Rdevel -q -e "z3 <- integer(3); hutilscpp::which_first(z3 == NaN)"
          Rdevel -q -e "z3 <- integer(3); hutilscpp::which_first(z3 != NaN)"
          Rdevel -q -e "z3 <- integer(3); hutilscpp::which_first(z3 >= 2147483647.1)"
          Rdevel -q -e "z3 <- integer(3); hutilscpp:::first_which(z3 >= 2147483647.1)"
          Rdevel -q -e "z3 <- integer(3); hutilscpp::which_last(z3 >= -2147483647.1)"
          Rdevel -q -e "z3 <- c(0L, 1:9); hutilscpp::which_last(z3 >= -2147483647.1)"
          Rdevel -q -e "z3 <- integer(3); hutilscpp::which_last(z3 >= -2147483647.1)"
          Rdevel -q -e "z3 <- c(0L, 1:9, -2147483647L); hutilscpp::which_last(z3 >= -2147483647)"
          Rdevel -q -e "z3 <- c(0L, 1:9, -2147483647L); hutilscpp::which_last(z3 < -2147483647)"
