name: Render and Deploy RMarkdown Website
'on': push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages(c('rcmdcheck', 'remotes', 'covr'), repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - name: codecov
        run: Rscript -e "covr::codecov()"
    container: rocker/verse:latest
  test-r-sanitizers:
    name: r-package (ubuntu-latest, R-devel, GCC ASAN/UBSAN)
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: rhub/rocker-gcc-san
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 5
          submodules: true
      - name: Install packages
        shell: bash
        run: |
          Rscript -e "TRUE || install.packages(c('devtools', , 'bench', 'parallel', 'testthat', 'TeXCheckR', 'withr', 'covr'), repos = 'https://cran.r-project.org', quiet=TRUE)"
          Rdevel -e "ip <- function(x) install.packages(x, quiet = TRUE, repos = 'https://cran.r-project.org'); ip(c('Rcpp', 'data.table', 'glue', 'hutils', 'magrittr', 'utils'))"
          Rdevel CMD build .
          Rdevel CMD INSTALL hutilscpp*.tar.gz
          Rdevel -e "z3 <- integer(3); hutilscpp::which_first(z3 == NaN); hutilscpp::which_first(z3 >= 2147483647.1)"
      - name: Run tests with sanitizers
        shell: bash
        run: |
          cd R-package/tests
          Rscriptdevel testthat.R 2>&1 > ubsan-tests.log
          cat ubsan-tests.log
          exit $(cat ubsan-tests.log | grep "runtime error" | wc -l)
